---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 4


provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[variant-call::_common]
      - recipe[variant-call::default]
    attributes:
