---
driver:
  name: vagrant
  customize:
    memory: 3072
    cpus: 2
    natdnshostresolver1: "on"
    natdnsproxy1: "on"
    nictype1: "virtio"
  network:
  - ["forwarded_port", {guest: 8042, host: 8042}]
  - ["forwarded_port", {guest: 8080, host: 8080}]
  - ["forwarded_port", {guest: 8088, host: 8088}]
  - ["forwarded_port", {guest: 50070, host: 50070}]
  - ["forwarded_port", {guest: 50075, host: 50075}]
  - ["private_network", ip: "192.168.0.2"]

provisioner:
  name: chef_solo

platforms:
# - name: centos-6.5
# - name: ubuntu-12.04
  - name: ubuntu-14.04
  

suites:
  - name: default
    run_list:
      - recipe[kagent::install]
      - recipe[hadoop::install]
      - recipe[hadoop::nn]
      - recipe[hadoop::rm]
      - recipe[hadoop::dn]
      - recipe[hadoop::nm]
      - recipe[hadoop::jhs]
      - recipe[hiway::install]
      - recipe[hiway::hiway_client]
      - recipe[hiway::hiway_worker]
      - recipe[hiway::cuneiform_client]
      - recipe[hiway::cuneiform_worker]
      - recipe[variant-call::tools]
      - recipe[variant-call::data]
      - recipe[variant-call::hdfs]
      - recipe[variant-call::workflow]

    attributes:
         dir:
           wf: "/home/hiway"
           data: "/home/hiway/data"
         hadoop:
            version: "2.7.1"
            nn:
               private_ips: ["10.0.2.15"]
            dn:
               private_ips: ["10.0.2.15"]
            rm:
               private_ips: ["10.0.2.15"]
            nm:
               private_ips: ["10.0.2.15"]
            jhs:
               private_ips: ["10.0.2.15"]
            cluster: vagrant
            yarn:
              user: "hiway"
              vcores: "3"
            mr:
              user: "hiway"
         hiway:
           user: "hiway"
         hdfs:
           user: "hiway"
         kmon:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         kagent:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         hiway:
            private_ips: ["10.0.2.15"]
            public_ips: ["10.0.2.15"]
         private_ips: ["10.0.2.15"]
         public_ips: ["10.0.2.15"]
         vagrant: "enabled"
